INSERT INTO COUNTRIES VALUES (1,'RU','RUS','Russian Federation',643);

INSERT INTO COUNTRIES VALUES (2,'SL','PA','Iceland',1),(3,'CL','Ross-shire','Bermuda',2),(4,'Alajuela','PD','Wallis and Futuna',3),(5,'WB','Antofagasta','Wallis and Futuna',4),(6,'ON','Arequipa','Western Sahara',5),(7,'SL','Coa','Bangladesh',6),(8,'SI','Extremadura','Isle of Man',7),(9,'Maharastra','KN','Jamaica',8),(10,'LX','Quebec','Brunei',9),(11,'Guanajuato','Lazio','Guadeloupe',10);
INSERT INTO COUNTRIES VALUES (12,'AK','Berlin','Vanuatu',11),(13,'MN','ATL','Cameroon',12),(14,'QLD','Hamburg','Sweden',13),(15,'Tamil Nadu','Sokoto','Uganda',14),(16,'Gävleborgs län','IL','Monaco',15),(17,'Stockholms län','Wielkopolskie','Mongolia',16),(18,'UP','Veracruz','South Africa',17),(19,'Vienna','Connacht','Albania',18),(20,'Ulster','SJ','Iraq',19),(21,'KK','Guanajuato','Madagascar',20);
INSERT INTO COUNTRIES  VALUES (22,'Burgenland','SK','Iceland',21),(23,'Mic','Punjab','Laos',22),(24,'ON','LA','Luxembourg',23),(25,'ANT','NSW','Taiwan',24),(26,'Orkney','Loreto','Iraq',25),(27,'PR','Uttar Pradesh','Ecuador',26),(28,'Istanbul','O''Higgins','Bahamas',27),(29,'MI','Antioquia','United Kingdom (Great Britain)',28),(30,'łódzkie','Jönköpings län','El Salvador',29),(31,'RM','WM','Palau',30);
INSERT INTO COUNTRIES  VALUES (32,'Heredia','Rio Grande do Sul','Greece',31),(33,'BC','Wie','Bouvet Island',32),(34,'Oklahoma','GL','Belgium',33),(35,'Bremen','IX','China',34),(36,'C','North Island','El Salvador',35),(37,'Uttar Pradesh','Gilgit Baltistan','Colombia',36),(38,'Wie','MS','Ecuador',37),(39,'VII','Ontario','Christmas Island',38),(40,'BU','KN','Bulgaria',39),(41,'L','Upper Austria','Seychelles',40);
INSERT INTO COUNTRIES  VALUES (42,'Metropolitana de Santiago','Puno','French Guiana',41),(43,'RS','East Java','Guatemala',42),(44,'NI','Haute-Normandie','Uganda',43),(45,'Wie','Sindh','Virgin Islands, British',44),(46,'SJ','Gye','Côte D''Ivoire (Ivory Coast)',45),(47,'Ontario','Atlántico','Lesotho',46),(48,'PUG','A','Slovakia',47),(49,'Antioquia','UP','Norfolk Island',48),(50,'Khyber Pakhtoonkhwa','Rio de Janeiro','San Marino',49),(51,'Hamburg','MG','Brunei',50);
INSERT INTO COUNTRIES VALUES (52,'O''Higgins','SI','Bermuda',51),(53,'Tula Oblast','Kentucky','Eritrea',52),(54,'Västra Götalands län','A','Norway',53),(55,'Gyeonggi','QC','Cambodia',54),(56,'West-Vlaanderen','LA','Congo, the Democratic Republic of the',55),(57,'North Island','Catalunya','Ethiopia',56),(58,'LA','AL','South Africa',57),(59,'West Nusa Tenggara','C','Heard Island and Mcdonald Islands',58),(60,'UP','MH','Belarus',59),(61,'NI','NS','Bouvet Island',60);
INSERT INTO COUNTRIES  VALUES (62,'ANT','Junín','Faroe Islands',61),(63,'Leinster','OY','Portugal',62),(64,'Biobío','Istanbul','Tuvalu',63),(65,'San José','Ist','Cocos (Keeling) Islands',64),(66,'Gaz','Sakhalin Oblast','Sudan',65),(67,'Quebec','Munster','Peru',66),(68,'Dolnośląskie','Angus','Norway',67),(69,'SI','LOM','Zimbabwe',68),(70,'MAG','FA','Svalbard and Jan Mayen Islands',69),(71,'Wie','West Bengal','Bahrain',70);
INSERT INTO COUNTRIES  VALUES (72,'MS','N.','Uganda',71),(73,'Manitoba','SI','French Southern Territories',72),(74,'UP','Andhra Pradesh','Vanuatu',73),(75,'Hawaii','SJ','China',74),(76,'M','WE','Taiwan',75),(77,'Hampshire','Comunitat Valenciana','Guam',76),(78,'SAR','CAM','Botswana',77),(79,'LD','South Australia','Liberia',78),(80,'North Island','NB','Bahrain',79),(81,'Merionethshire','GB','Armenia',80);
INSERT INTO COUNTRIES  VALUES (82,'NI','ARE','Brazil',81),(83,'Cusco','South Jeolla','Somalia',82),(84,'Niger','Metropolitana de Santiago','Azerbaijan',83),(85,'Overijssel','SN','Swaziland',84),(86,'Coquimbo','Alajuela','Indonesia',85),(87,'Sindh','ID','Oman',86),(88,'Principado de Asturias','South Sumatra','El Salvador',87),(89,'ANT','Zeeland','Madagascar',88),(90,'OG','CN','Côte D''Ivoire (Ivory Coast)',89),(91,'North Island','ANT','Australia',90);
INSERT INTO COUNTRIES VALUES (92,'Schleswig-Holstein','HH','Mauritius',91),(93,'Vienna','BOL','Uruguay',92),(94,'Wie','Dalarnas län','Uganda',93),(95,'MI','C','Cape Verde',94),(96,'Bursa','Balochistan','Indonesia',95),(97,'BOL','LA','Morocco',96),(98,'QLD','H','Canada',97),(99,'Michoacán','Vbg','Northern Mariana Islands',98),(100,'CDM','North Island','Latvia',99),(101,'CT','NB','Mali',100);